
# Site settings
title: BSides Munich 2021
subtitle: "A free security conference in the heart of Bavaria"
url: "https://2021.bsidesmunich.org" # the base hostname & protocol for your site
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"
timezone: Europe/Berlin

# Build settings
markdown: kramdown

collections:
  talks:
    output: true #Does not work
    permalink: /:collection/:title/
#    /:collection/:title/index.html
  workshops:
    output: true #Does not work
    permalink: /:collection/:title/
#    permalink: /:collection/:title

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

imprint:
  #name: "BSides Munich, Mr. Frederic Mohr"
  name: "MUC:SEC e.V."
  addressco: "c/o LastBreach"
  address: "Rohrauerstraße 70, 81477 München"
  email: "manager [at] bsidesmunich [dot] org"
  #phone: "+49 89
  chair: Christoph Kemetmüller
  vicechair: Ana Oprea


conference:
  # contact e-mail, e.g., for sponsors
  email: organizers@bsidesmunich.org
  twitter: https://twitter.com/bsidesmunich
  notice: 

  sponsors:
    contact: sponsors (at) bsidesmunich (dot) org
    #show the sponsors in the footer of every page
    lookingfor: true
    footer: false #BETA
    # sponsor logos should all have the same format (at least width)
# uncomment it to fill sponsors in

    community:
    - name: Elbsides
      logo: /img/sponsors/elbsides.png
      uri: https://2021.elbsides.de

    helium:
    - name: Blaze Information Security Lda.
      logo: /img/sponsors/Blaze_Information_Security_Logo_Horizontal_Main_Yellow_Large.png
      uri: https://www.blazeinfosec.com/
    - name: sepago GmbH
      logo: /img/sponsors/sepago_print_gross_freigestellt-klein.png
      uri: https://www.sepago.de/en/home/
    - name: YES WE HACK
      logo: /img/sponsors/YWH-black.png
      uri: https://www.yeswehack.com 

    neon:
    - name: CYRES Consulting Services GmbH
      logo: /img/sponsors/Cyres_Logo_4C.png
      uri: http://cyres-consulting.com/
    - name: Google
      logo: /img/sponsors/Google_FullColor_hdpi_270x89px.png
      uri:  https://www.google.com
    - name: Huawei
      logo: /img/sponsors/huawei-1.png
      uri: https://www.huawei.com/en/
    - name: NSIDE ATTACK LOGIC GmbH
      logo: /img/sponsors/NSIDE.png
      uri:  https://www.nsideattacklogic.de/
    - name: SIEMENS
      logo: /img/sponsors/siemens.png
      uri: https://siemens.com/cert/

    argon:
    - name: Maltego Technologies GmbH
      logo: /img/sponsors/Maltego-Logo-Horizontal-Black.png
      uri: https://www.maltego.com

    krypton:
    - name: Graylog
      logo: /img/sponsors/graylog.png
      uri: https://www.graylog.org/

  links:
    sponsorpackage_en_uri: /files/BSidesMunich2021Sponsorship-English.pdf
    sponsorpackage_de_uri: /files/BSidesMunich2021Sponsorship-Deutsch.pdf
    cfw_uri: 
    cfp_uri: https://easychair.org/conferences/?conf=bsidesmesh21
    contickets_uri: 
    contickets_state: 
      
  dates: 
    deadline_tickets: 
    deadline_cfp: 2021-04-07
    deadline_notification: 2021-04-19
    deadline_recording: 2021-06-01
    workshops: 2021-06-20
    conference: 2021-06-21 -- 22

  venue:
    workshopsday:
      address: Virtual
      details: ""
      gps: 
    conferenceday:
      address: Virtual
      details: ""
      gps:
  archive:
    a2020:
      title: "BSMaaS:2020.08.23"
      participants: 661
      presentations: 8
      workshops: 0
      hours: 5
      website_uri: https://2020.bsidesmunich.org
      recordings_uri: https://www.youtube.com/playlist?list=PL8N5HiRDvZ-eMEwvQmnw3u26CubSr02cD
      slider:
      - src: img/slider2020/header.png
compress_html:
  clippings: all
  comments: all
  ignore:
    envs: []
  blanklines: false
  profile: false

exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "Makefile"
  - "INSTALL.txt"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

pre_build:
  commands:
    - export LC_ALL="C.UTF-8"
    - export LANG="en_US.UTF-8"
    - export LANGUAGE="en_US.UTF-8"
